### ISSUE TITLE
This doesn't look safe

### ISSUE THREAD

**Issue by CreativZivv** [RiaxWii/ECLIPSE-Reborn#1]

**Comment by RiaxWii** [comment]
Hello,

As I have already mentioned, avoid asking these questions.
Here is the VirusTotal (anti-virus engines) of ECLIPSE:  https://bit.ly/3KWXclo

ECLIPSE will never be open-source, I will rather damage the reputation than having countless reuploads like my old software.
If you need help, contact me on Discord.
